# Generated by Django 4.1.3 on 2022-11-13 16:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_receptiontime_remove_workingday_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timestable',
            name='reception',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='receptiontime',
            name='reception',
            field=models.TimeField(verbose_name='Запись к врачу'),
        ),
        migrations.AlterField(
            model_name='timestable',
            name='end_time',
            field=models.TimeField(verbose_name='Конец приема'),
        ),
        migrations.AlterField(
            model_name='timestable',
            name='start_time',
            field=models.TimeField(verbose_name='Начало приема'),
        ),
    ]
