# Generated by Django 4.1.3 on 2022-11-13 18:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_timestable_reception'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestable',
            name='reception',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), default=list, size=None),
        ),
    ]
